[tox]
envlist = py312

[gh-actions]
python =
    3.12: py312

[testenv]
description = run the unit tests with pytest under {basepython}
package = wheel
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pytest tests
